#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("YWWACP.Resource", IsApplication=true)]

namespace YWWACP
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxBind = global::YWWACP.Resource.Attribute.MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxDropDownItemTemplate = global::YWWACP.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxGroupItemTemplate = global::YWWACP.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxItemTemplate = global::YWWACP.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxLang = global::YWWACP.Resource.Attribute.MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxSource = global::YWWACP.Resource.Attribute.MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxTemplate = global::YWWACP.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Id.MvvmCrossTagId = global::YWWACP.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Binding.Droid.Resource.Id.MvxBindingTagUnique = global::YWWACP.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding = global::YWWACP.Resource.Styleable.MvxBinding;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxBind = global::YWWACP.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxLang = global::YWWACP.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl = global::YWWACP.Resource.Styleable.MvxControl;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl_MvxTemplate = global::YWWACP.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView = global::YWWACP.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::YWWACP.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView = global::YWWACP.Resource.Styleable.MvxImageView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView_MvxSource = global::YWWACP.Resource.Styleable.MvxImageView_MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView = global::YWWACP.Resource.Styleable.MvxListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::YWWACP.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxItemTemplate = global::YWWACP.Resource.Styleable.MvxListView_MvxItemTemplate;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_right = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_up = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f080001
			public const int categories_activities = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int categories_array = 2131230720;
			
			// aapt resource value: 0x7f080002
			public const int categories_food = 2131230722;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int MvxDropDownItemTemplate = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int MvxGroupItemTemplate = 2130771973;
			
			// aapt resource value: 0x7f010003
			public const int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010006
			public const int MvxSource = 2130771974;
			
			// aapt resource value: 0x7f010002
			public const int MvxTemplate = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int arrow_left = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int arrow_right = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int border = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ButtonSignUpStyle = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int edit_text_style = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ProfilePicture = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int recipeIcon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int splash = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int MvvmCrossTagId = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int MvxBindingTagUnique = 2131034113;
			
			// aapt resource value: 0x7f05004a
			public const int addBtn = 2131034186;
			
			// aapt resource value: 0x7f050017
			public const int btnAddPlan = 2131034135;
			
			// aapt resource value: 0x7f05000c
			public const int btnCancelThread = 2131034124;
			
			// aapt resource value: 0x7f050016
			public const int btnCommunity = 2131034134;
			
			// aapt resource value: 0x7f050012
			public const int btnDiary = 2131034130;
			
			// aapt resource value: 0x7f05003e
			public const int btnDone = 2131034174;
			
			// aapt resource value: 0x7f050008
			public const int btnExisting = 2131034120;
			
			// aapt resource value: 0x7f050013
			public const int btnHealthPlan = 2131034131;
			
			// aapt resource value: 0x7f050004
			public const int btnMyThreads = 2131034116;
			
			// aapt resource value: 0x7f050007
			public const int btnNew = 2131034119;
			
			// aapt resource value: 0x7f050003
			public const int btnNewThread = 2131034115;
			
			// aapt resource value: 0x7f050014
			public const int btnProfile = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int btnRecipes = 2131034133;
			
			// aapt resource value: 0x7f05000d
			public const int btnSubmitThread = 2131034125;
			
			// aapt resource value: 0x7f050010
			public const int btnToday = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int btnTomorrow = 2131034129;
			
			// aapt resource value: 0x7f05000f
			public const int btnYesterday = 2131034127;
			
			// aapt resource value: 0x7f050044
			public const int buttonSaveText = 2131034180;
			
			// aapt resource value: 0x7f050006
			public const int calendarView1 = 2131034118;
			
			// aapt resource value: 0x7f050049
			public const int cancelBtn = 2131034185;
			
			// aapt resource value: 0x7f05000e
			public const int dayPicker = 2131034126;
			
			// aapt resource value: 0x7f05000b
			public const int editTxtQuestion = 2131034123;
			
			// aapt resource value: 0x7f050009
			public const int editTxtTitle = 2131034121;
			
			// aapt resource value: 0x7f05004b
			public const int grid = 2131034187;
			
			// aapt resource value: 0x7f050041
			public const int imageView1 = 2131034177;
			
			// aapt resource value: 0x7f050002
			public const int linearLayoutWrapTopButtons = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int listViewCommunity = 2131034117;
			
			// aapt resource value: 0x7f050047
			public const int recepieImage = 2131034183;
			
			// aapt resource value: 0x7f050048
			public const int recepieText = 2131034184;
			
			// aapt resource value: 0x7f050031
			public const int spinnerActivitiesFriday = 2131034161;
			
			// aapt resource value: 0x7f05001d
			public const int spinnerActivitiesMonday = 2131034141;
			
			// aapt resource value: 0x7f050036
			public const int spinnerActivitiesSaturday = 2131034166;
			
			// aapt resource value: 0x7f05003b
			public const int spinnerActivitiesSunday = 2131034171;
			
			// aapt resource value: 0x7f05002c
			public const int spinnerActivitiesThursday = 2131034156;
			
			// aapt resource value: 0x7f050022
			public const int spinnerActivitiesTuesday = 2131034146;
			
			// aapt resource value: 0x7f050027
			public const int spinnerActivitiesWednesday = 2131034151;
			
			// aapt resource value: 0x7f05000a
			public const int spinnerCategories = 2131034122;
			
			// aapt resource value: 0x7f050033
			public const int spinnerFoodFriday = 2131034163;
			
			// aapt resource value: 0x7f05001f
			public const int spinnerFoodMonday = 2131034143;
			
			// aapt resource value: 0x7f050038
			public const int spinnerFoodSaturday = 2131034168;
			
			// aapt resource value: 0x7f05003d
			public const int spinnerFoodSunday = 2131034173;
			
			// aapt resource value: 0x7f05002e
			public const int spinnerFoodThursday = 2131034158;
			
			// aapt resource value: 0x7f050024
			public const int spinnerFoodTuesday = 2131034148;
			
			// aapt resource value: 0x7f050029
			public const int spinnerFoodWednesday = 2131034153;
			
			// aapt resource value: 0x7f05003f
			public const int tableLayout1 = 2131034175;
			
			// aapt resource value: 0x7f050040
			public const int tableRow1 = 2131034176;
			
			// aapt resource value: 0x7f050042
			public const int tableRow2 = 2131034178;
			
			// aapt resource value: 0x7f050045
			public const int tableRow3 = 2131034181;
			
			// aapt resource value: 0x7f050046
			public const int tableRow4 = 2131034182;
			
			// aapt resource value: 0x7f05001b
			public const int textView1 = 2131034139;
			
			// aapt resource value: 0x7f05002a
			public const int textView10 = 2131034154;
			
			// aapt resource value: 0x7f05002b
			public const int textView11 = 2131034155;
			
			// aapt resource value: 0x7f05002d
			public const int textView12 = 2131034157;
			
			// aapt resource value: 0x7f05002f
			public const int textView13 = 2131034159;
			
			// aapt resource value: 0x7f050030
			public const int textView14 = 2131034160;
			
			// aapt resource value: 0x7f050032
			public const int textView15 = 2131034162;
			
			// aapt resource value: 0x7f050034
			public const int textView16 = 2131034164;
			
			// aapt resource value: 0x7f050035
			public const int textView17 = 2131034165;
			
			// aapt resource value: 0x7f050037
			public const int textView18 = 2131034167;
			
			// aapt resource value: 0x7f050039
			public const int textView19 = 2131034169;
			
			// aapt resource value: 0x7f05001c
			public const int textView2 = 2131034140;
			
			// aapt resource value: 0x7f05003a
			public const int textView20 = 2131034170;
			
			// aapt resource value: 0x7f05003c
			public const int textView21 = 2131034172;
			
			// aapt resource value: 0x7f05001e
			public const int textView3 = 2131034142;
			
			// aapt resource value: 0x7f050020
			public const int textView4 = 2131034144;
			
			// aapt resource value: 0x7f050021
			public const int textView5 = 2131034145;
			
			// aapt resource value: 0x7f050023
			public const int textView6 = 2131034147;
			
			// aapt resource value: 0x7f050025
			public const int textView7 = 2131034149;
			
			// aapt resource value: 0x7f050026
			public const int textView8 = 2131034150;
			
			// aapt resource value: 0x7f050028
			public const int textView9 = 2131034152;
			
			// aapt resource value: 0x7f050019
			public const int txtViewCategory = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int txtViewContent = 2131034138;
			
			// aapt resource value: 0x7f050018
			public const int txtViewTitle = 2131034136;
			
			// aapt resource value: 0x7f050043
			public const int userInfo = 2131034179;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Community = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Dialog_calendar = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Dialog_ChooseHealthPlan = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Dialog_New_Thread = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Diary = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int FirstView = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int HealthPlan = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int ListView_Row = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int NewHealthPlan = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Profile = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int recipeDialogView = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int RecipeMain = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Recipes = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int SplashScreen = 2130903053;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070000
			public const int ApplicationName = 2131165184;
			
			// aapt resource value: 0x7f070005
			public const int Community = 2131165189;
			
			// aapt resource value: 0x7f070001
			public const int Diary = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int Health_Plan = 2131165187;
			
			// aapt resource value: 0x7f070008
			public const int My_Threads = 2131165192;
			
			// aapt resource value: 0x7f070007
			public const int New_Thread = 2131165191;
			
			// aapt resource value: 0x7f070002
			public const int Profile = 2131165186;
			
			// aapt resource value: 0x7f070004
			public const int Recipes = 2131165188;
			
			// aapt resource value: 0x7f07000a
			public const int Title = 2131165194;
			
			// aapt resource value: 0x7f070006
			public const int Today = 2131165190;
			
			// aapt resource value: 0x7f070009
			public const int Your_Question = 2131165193;
			
			// aapt resource value: 0x7f07000b
			public const int cancelThread = 2131165195;
			
			// aapt resource value: 0x7f07000d
			public const int category_prompt = 2131165197;
			
			// aapt resource value: 0x7f07000c
			public const int submitThread = 2131165196;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Splash = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int dialog_animation = 2131099649;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxExpandableListView = new int[] {
					2130771973};
			
			// aapt resource value: 0
			public const int MvxExpandableListView_MvxGroupItemTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771974};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
