#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("YWWACP.Resource", IsApplication=true)]

namespace YWWACP
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int categories_array = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int arrow_left = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int arrow_right = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ButtonSignUpStyle = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int edit_text_style = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060007
			public const int btnCancelThread = 2131099655;
			
			// aapt resource value: 0x7f060011
			public const int btnCommunity = 2131099665;
			
			// aapt resource value: 0x7f06000d
			public const int btnDiary = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int btnHealthPlan = 2131099662;
			
			// aapt resource value: 0x7f060002
			public const int btnMyThreads = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int btnNewThread = 2131099649;
			
			// aapt resource value: 0x7f06000f
			public const int btnProfile = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int btnRecipes = 2131099664;
			
			// aapt resource value: 0x7f060008
			public const int btnSubmitThread = 2131099656;
			
			// aapt resource value: 0x7f06000b
			public const int btnToday = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int btnTomorrow = 2131099660;
			
			// aapt resource value: 0x7f06000a
			public const int btnYesterday = 2131099658;
			
			// aapt resource value: 0x7f060003
			public const int calendarView1 = 2131099651;
			
			// aapt resource value: 0x7f060009
			public const int dayPicker = 2131099657;
			
			// aapt resource value: 0x7f060006
			public const int editTxtQuestion = 2131099654;
			
			// aapt resource value: 0x7f060004
			public const int editTxtTitle = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int linearLayoutWrapTopButtons = 2131099648;
			
			// aapt resource value: 0x7f060005
			public const int spinnerCategories = 2131099653;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Community = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Dialog_calendar = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Dialog_New_Thread = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Diary = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Recipes = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040005
			public const int Community = 2130968581;
			
			// aapt resource value: 0x7f040001
			public const int Diary = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int Health_Plan = 2130968579;
			
			// aapt resource value: 0x7f040008
			public const int My_Threads = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int New_Thread = 2130968583;
			
			// aapt resource value: 0x7f040002
			public const int Profile = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int Recipes = 2130968580;
			
			// aapt resource value: 0x7f04000a
			public const int Title = 2130968586;
			
			// aapt resource value: 0x7f040006
			public const int Today = 2130968582;
			
			// aapt resource value: 0x7f040009
			public const int Your_Question = 2130968585;
			
			// aapt resource value: 0x7f04000b
			public const int cancelThread = 2130968587;
			
			// aapt resource value: 0x7f04000d
			public const int category_prompt = 2130968589;
			
			// aapt resource value: 0x7f04000c
			public const int submitThread = 2130968588;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
